name: Build AzureDeploy.json

on:
  push:
     paths:
      - '**.bicep'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: checkout
        uses: actions/checkout@v2

      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./bicep/main.bicep
          outputFilePath: ./azuredeploy.json
    
      - name: push-azuredeploy
        run: |
             git config user.name  ${{ github.actor }}
             git config user.email  ${{ github.actor }}@github.com
             git add ./azuredeploy.json
             git commit --allow-empty -m "Updating AzureDeploy.json for one click deploy"
             git push
